// Package crash is the cockpit's panic-recovery and crash-report
// subsystem. It exists to turn "panic on the goroutine that holds
// the terminal" into "render a friendly message in the affected
// pane (or restore the terminal and print one), give the user an
// error code, and write a structured log they can hand to support".
//
// Three layers of recovery, in order of preference (most local
// first):
//
//  1. Per-tab Draw / HandleEvent -- Catch wraps a single tab's
//     render or event handler. A panic there shows the broken tab
//     as an inline error placeholder; F1..F3 to other tabs still
//     work and the user can keep operating.
//  2. Main event-loop iteration -- Catch wraps each iteration of
//     App.Run's for-loop body. A panic anywhere outside the per-
//     tab wrappers (chrome rendering, event-dispatch wiring,
//     redraw scheduling) lands here, is logged, surfaces as a
//     notification, and the loop continues. The app stays alive.
//  3. main() outermost -- last-resort defer-recover for panics
//     that escape every prior layer (e.g. tcell init blowing up
//     before Run even starts, or a panic during the controlled
//     shutdown path itself). Finalizes the terminal cleanly,
//     prints the friendly message + error code, exits non-zero.
//
// The error code is a fresh 8-char hex per panic. Same code lands
// in the log filename and in the user-facing message, so support
// can ask "what's your code?" and pull the matching log.
package crash

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"runtime/debug"
	"strings"
	"time"
)

// Report is the structured record of a single panic. Generated by
// Catch on recover; consumed by WriteLog + the user-facing message
// helpers.
type Report struct {
	// Code is the short error code the user is told to quote when
	// contacting support. 8 hex chars, fresh per panic.
	Code string
	// At is the wall-clock time the panic was caught.
	At time.Time
	// Label identifies the recovery site. Set by the Catch caller --
	// "draw:concepts", "event:concepts", "main-loop", etc. Surfaces in
	// the crash log so a support engineer knows which surface fell over.
	Label string
	// Value is the runtime.Error / string / arbitrary value the
	// panicking code passed to panic(). Format-stringified at recover
	// time so the report stays valid after the goroutine unwinds.
	Value string
	// Stack is the goroutine stack at panic time (runtime/debug.Stack
	// captured inside the deferred recover, so it includes the panic
	// frame).
	Stack string
	// LogPath is the absolute path WriteLog wrote the report to. Empty
	// until WriteLog runs.
	LogPath string
}

// Catch runs fn under a deferred recover. If fn panics, the panic is
// caught, a Report is built, the log is written, and the report is
// returned (caller decides what user-facing UI to render). If fn
// returns normally, Catch returns nil.
//
// label is the recovery-site identifier ("draw:concepts" etc.). It
// goes into the crash log so support knows where the panic happened.
func Catch(label string, fn func()) (report *Report) {
	defer func() {
		if r := recover(); r != nil {
			report = newReport(label, r)
			_ = WriteLog(report)
		}
	}()
	fn()
	return nil
}

// newReport assembles a Report from a recover() value. Captures the
// stack inside the deferred recover so the panic frames are present.
// Both the panic value and the stack go through SanitizeForCrashLog
// to scrub token-shaped strings before they ever land on disk -- the
// crash log is mode 0600 but is also the file support engineers see
// when a user pastes it into a ticket, and tokens in stack frames
// (locals from closures, function arguments) are a leak surface even
// at 0600.
func newReport(label string, panicValue any) *Report {
	return &Report{
		Code:  shortCode(),
		At:    time.Now().UTC(),
		Label: strings.TrimSpace(label),
		Value: SanitizeForCrashLog(fmt.Sprintf("%v", panicValue)),
		Stack: SanitizeForCrashLog(string(debug.Stack())),
	}
}

// shortCode mints a fresh 8-char hex error code. Used as the
// user-visible "tell support this number" identifier and also as
// the suffix on the crash-log filename so the two correlate.
//
// Pure random rather than a hash of the panic value -- two distinct
// panic instances of the same underlying bug get distinct codes,
// matching distinct log files. Easier for support to triage.
func shortCode() string {
	buf := make([]byte, 4) // 4 bytes -> 8 hex chars
	if _, err := rand.Read(buf); err != nil {
		// Fall back to a timestamp-derived code so we always produce
		// SOMETHING. Collisions are theoretically possible but the
		// log file's full timestamp disambiguates.
		return fmt.Sprintf("%08x", time.Now().UnixNano()&0xffffffff)
	}
	return hex.EncodeToString(buf)
}

// LogDir returns the directory crash logs are written to. Creates
// it on demand; safe to call concurrently.
func LogDir() string {
	home, err := os.UserHomeDir()
	if err != nil {
		// Last resort: /tmp. Better than dropping the log on the floor
		// when the user's home dir is unreadable (mounted from a broken
		// network share, etc.).
		return filepath.Join(os.TempDir(), "memql-cockpit-crashes")
	}
	return filepath.Join(home, ".memql", "cockpit-crashes")
}

// WriteLog serializes the report to a human-readable file under
// LogDir(). Filename pattern:
//
//	<ISO8601-ish-timestamp>-<code>.log
//
// Returns the path on success; on failure leaves report.LogPath
// empty and returns the error so the caller can decide whether to
// surface it (typically: log to stderr and keep going -- the user
// already has bigger problems).
func WriteLog(r *Report) error {
	if r == nil {
		return fmt.Errorf("nil report")
	}
	dir := LogDir()
	if err := os.MkdirAll(dir, 0700); err != nil {
		return fmt.Errorf("mkdir crash dir: %w", err)
	}
	name := fmt.Sprintf("%s-%s.log", r.At.Format("20060102-150405"), r.Code)
	path := filepath.Join(dir, name)
	body := fmt.Sprintf(
		"memql-cockpit crash report\n"+
			"=========================\n"+
			"code:       %s\n"+
			"timestamp:  %s\n"+
			"label:      %s\n"+
			"panic:      %s\n"+
			"\n"+
			"stack:\n"+
			"%s\n",
		r.Code,
		r.At.Format(time.RFC3339Nano),
		r.Label,
		r.Value,
		r.Stack,
	)
	if err := os.WriteFile(path, []byte(body), 0600); err != nil {
		return fmt.Errorf("write crash log: %w", err)
	}
	r.LogPath = path
	return nil
}

// UserMessage formats the friendly multi-line message shown after a
// fatal crash. Includes the code, the log path, and the
// contact-support hint. Designed to be printed to stderr after
// tcell has been finalized so the terminal is in a usable state.
func UserMessage(r *Report) string {
	if r == nil {
		return "memql-cockpit hit an unexpected error. Please contact support.\n"
	}
	logHint := "(no crash log was written; check filesystem permissions on ~/.memql/)"
	if r.LogPath != "" {
		logHint = fmt.Sprintf("Crash log: %s", r.LogPath)
	}
	return fmt.Sprintf(
		"\n"+
			"  memql-cockpit hit an unexpected error and could not continue.\n"+
			"\n"+
			"  Error code: %s\n"+
			"  %s\n"+
			"\n"+
			"  Please contact support and include the error code above.\n"+
			"\n",
		r.Code,
		logHint,
	)
}
